---@class UnitEvents
UNIT_EVENTS = {}
UNIT_EVENTS.START = 'onStart'
UNIT_EVENTS.STOP = 'onStop'

---@class SystemEvents
SYSTEM_EVENTS = {}
SYSTEM_EVENTS.ACTION_LOOP = 'onActionLoop'
SYSTEM_EVENTS.ACTION_START = 'onActionStart'
SYSTEM_EVENTS.ACTION_STOP = 'onActionStop'
SYSTEM_EVENTS.INPUT_TEXT = 'onInputText'
SYSTEM_EVENTS.UPDATE = 'onUpdate'

---@class LuaActions
LUA_ACTIONS = {}
LUA_ACTIONS.FORWARD = "forward"
LUA_ACTIONS.BACKWARD = "backward"
LUA_ACTIONS.YAWLEFT = "yawleft"
LUA_ACTIONS.YAWRIGHT = "yawright"
LUA_ACTIONS.STRAFELEFT = "strafeleft"
LUA_ACTIONS.STRAFERIGHT = "straferight"
LUA_ACTIONS.LEFT = "left"
LUA_ACTIONS.RIGHT = "right"
LUA_ACTIONS.UP = "up"
LUA_ACTIONS.DOWN = "down"
LUA_ACTIONS.GROUNDALTITUDEUP = "groundaltitudeup"
LUA_ACTIONS.GROUNDALTITUDEDOWN = "groundaltitudedown"
LUA_ACTIONS.LALT = "lalt"
LUA_ACTIONS.LSHIFT = "lshift"
LUA_ACTIONS.GEAR = "gear"
LUA_ACTIONS.LIGHT = "light"
LUA_ACTIONS.BRAKE = "brake"
LUA_ACTIONS.OPTION1 = "option1"
LUA_ACTIONS.OPTION2 = "option2"
LUA_ACTIONS.OPTION3 = "option3"
LUA_ACTIONS.OPTION4 = "option4"
LUA_ACTIONS.OPTION5 = "option5"
LUA_ACTIONS.OPTION6 = "option6"
LUA_ACTIONS.OPTION7 = "option7"
LUA_ACTIONS.OPTION8 = "option8"
LUA_ACTIONS.OPTION9 = "option9"
LUA_ACTIONS.LEFTMOUSE = "leftmouse"
LUA_ACTIONS.STOPENGINES = "stopengines"
LUA_ACTIONS.SPEEDUP = "speedup"
LUA_ACTIONS.SPEEDDOWN = "speeddown"
LUA_ACTIONS.ANTIGRAVITY = "antigravity"
LUA_ACTIONS.BOOSTER = "booster"